### PR TITLE
Added two new quotes from Game of Thrones

### PR DESCRIPTION
**Pull request by MladenZeljic**
Added two quotes from Game of Thrones. Reformatted the code a bit. Warning: There are duplicate quotes in the data file from before, so the test was failing, so this should be fixed!

### CODE REVIEW

**Comment by MladenZeljic** [comment]
@NikhilNamal17 This pr is ready for review, but there are duplicate quotes in data file from before (there were not introduced by me).

**Comment by NikhilNamal17** [comment]
@MladenZeljic your branch has merge conflicts pls resolve and pr again

**Comment by NikhilNamal17** [comment]
@MladenZeljic I removed all duplicates just clone it now and you can add your quote.

**Comment by NikhilNamal17** [comment]
@MladenZeljic I'm closing this pr just so that I can add some automation, pls don't mind and pr again

**Comment by MladenZeljic** [comment]
Ok, no problem thanks! :-)

**Pull request closed without merging**
