### PR TITLE
Added Movie qoute for judge dredd (original 2001)

### PR DESCRIPTION
**Pull request by GunnerJnr**
{
      "quote": "I never broke the Law! I am the law!",
      "movie": "Judge Dredd",
      "type": "Movie",
      "year": 2001
 }

### CODE REVIEW

**Comment by GunnerJnr** [comment]
{
      "quote": "You better watch you mouth, you flippy flappy piece of boom boom. I've known you since you were born and you were a snake baby back then. Snake babies can't drink mad dog 20 20. Nuh uh, sure can't ya fiddle stick munching thumb sitter.",
      "movie": "Doom",
      "type": "Movie",
      "year": 2006
}

**Comment by NikhilNamal17** [comment]
@GunnerJnr your branch has merge conflicts, can you pls solve and send pr again.

**Comment by GunnerJnr** [comment]
That’s strange when I made the request it said there were not any conflicts, thanks for letting me know I’ll take a look as soon as I’m back home tomorrow and sort them out. Apologies 🤔

**Comment by NikhilNamal17** [comment]
@GunnerJnr  your branch has merge conflicts, can you pls solve and pr again.

**Pull request closed without merging**
