### PR TITLE
Moulin Rouge Movie added

### PR DESCRIPTION
**Pull request by gennipher**

### CODE REVIEW

**Comment by NikhilNamal17** [comment]
@gennipher your branch has merge conflicts, can you pls solve and pr again.

**Comment by gennipher** [comment]
I don't know what I did wrong. Can you help me ? Please

**Comment by NikhilNamal17** [comment]
@gennipher I justed deleted all duplicate quotes and your version of code still has old quotes. If you git pull and add your quote again, it will be solved.

**Comment by gennipher** [comment]
I think I done well now, can you take a look for me? Thanks

**Comment by NikhilNamal17** [comment]
@gennipher sorry but your branch still has a couple of conflicts, if you can solve and pr again i'll merge it.

**Pull request closed without merging**
