### PR TITLE
Add a function to get quotes by year

### PR DESCRIPTION
**Pull request by Snipey**
Also did some refactoring of the main file

### CODE REVIEW

**Comment by NikhilNamal17** [comment]
@Snipey I added your method implemented with forEach().

**Comment by Snipey** [comment]
Thanks I guess?

**Comment by Snipey** [comment]
I am a little upset you just used my contribution for Hacktober as your own because you could not wait for me to fix the pr you requested changes to. @NikhilNamal17 It is against the spirit of open source even if i included something you did not like. I could have still fixed it.

**Comment by NikhilNamal17** [comment]
@Snipey I'm really sorry. I apologize for my mistake, I was just impatient to add this beautiful method to codebase. I accept I accidentally broke the spirit of open source. Now what I can do is, I'll delete my method, you refactor your code, send pr again. I'm so sorry my mistake @Snipey

**Pull request closed without merging**
